# Generated by Django 3.0.7 on 2020-06-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='description',
            field=models.CharField(help_text='Descripcion de la categoría', max_length=100, unique=True, verbose_name='Descripción'),
        ),
    ]
