# Generated by Django 3.0.7 on 2020-06-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_auto_20200618_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='description',
            field=models.CharField(blank=None, help_text='Descripcion de la categoría', max_length=100, unique=True, verbose_name='Descripción'),
        ),
    ]
