# Generated by Django 3.0.7 on 2020-06-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_auto_20200622_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='description',
            field=models.CharField(help_text='Descripcion de la categoría', max_length=100, verbose_name='Descripción'),
        ),
    ]
