# Generated by Django 3.0.7 on 2020-07-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_auto_20200622_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ultima_compra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
