# Generated by Django 3.0.7 on 2020-07-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0010_auto_20200704_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='updatedUsu',
            field=models.IntegerField(blank=True, null=True, verbose_name='user.User'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='updatedUsu',
            field=models.IntegerField(blank=True, null=True, verbose_name='user.User'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='updatedUsu',
            field=models.IntegerField(blank=True, null=True, verbose_name='user.User'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='updatedUsu',
            field=models.IntegerField(blank=True, null=True, verbose_name='user.User'),
        ),
    ]
