# Generated by Django 3.0.7 on 2020-06-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_auto_20200618_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
