# Generated by Django 3.0.7 on 2020-06-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0004_auto_20200620_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Jurídica', 'Jurídica'), ('Natural', 'Natural')], default='Natural', max_length=10),
        ),
    ]
