# Generated by Django 3.0.7 on 2020-06-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0006_auto_20200621_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
    ]
