# Generated by Django 3.0.7 on 2020-06-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0011_facturaenc_facturdet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Natural', 'Natural'), ('Jurídica', 'Jurídica')], default='Natural', max_length=10),
        ),
    ]
