# Generated by Django 3.0.7 on 2020-07-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0015_auto_20200702_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaenc',
            name='nrofactura',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Jurídica', 'Jurídica'), ('Natural', 'Natural')], default='Natural', max_length=10),
        ),
    ]
