# Generated by Django 3.0.7 on 2020-07-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0016_auto_20200702_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturdet',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='facturdet',
            name='total',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Natural', 'Natural'), ('Jurídica', 'Jurídica')], default='Natural', max_length=10),
        ),
    ]
