# Generated by Django 3.0.7 on 2020-07-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0019_auto_20200729_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Jurídica', 'Jurídica'), ('Natural', 'Natural')], default='NAT', max_length=10),
        ),
    ]
