# Generated by Django 3.0.7 on 2020-06-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_comprasdet_comprasenc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprasenc',
            old_name='fehca_factura',
            new_name='fecha_factura',
        ),
        migrations.RenameField(
            model_name='comprasenc',
            old_name='no_facturacion',
            new_name='no_factura',
        ),
    ]
